#include "UnitTypes.h"

using namespace sc2;

namespace sc2util {

	bool IsMineral(sc2::UNIT_TYPEID type) {
		switch (type) {
		case  UNIT_TYPEID::NEUTRAL_MINERALFIELD:case  UNIT_TYPEID::NEUTRAL_MINERALFIELD750:case  UNIT_TYPEID::NEUTRAL_RICHMINERALFIELD:
		case  UNIT_TYPEID::NEUTRAL_RICHMINERALFIELD750:case  UNIT_TYPEID::NEUTRAL_PURIFIERMINERALFIELD:case  UNIT_TYPEID::NEUTRAL_PURIFIERMINERALFIELD750:
		case  UNIT_TYPEID::NEUTRAL_PURIFIERRICHMINERALFIELD:case  UNIT_TYPEID::NEUTRAL_PURIFIERRICHMINERALFIELD750:case  UNIT_TYPEID::NEUTRAL_LABMINERALFIELD:
		case  UNIT_TYPEID::NEUTRAL_LABMINERALFIELD750:case  UNIT_TYPEID::NEUTRAL_BATTLESTATIONMINERALFIELD:case  UNIT_TYPEID::NEUTRAL_BATTLESTATIONMINERALFIELD750:
			return true;
		}
		return false;
	}

	bool IsVespene(sc2::UNIT_TYPEID type) {
		switch (type) {
		case  UNIT_TYPEID::NEUTRAL_VESPENEGEYSER:case  UNIT_TYPEID::NEUTRAL_PROTOSSVESPENEGEYSER:case  UNIT_TYPEID::NEUTRAL_SHAKURASVESPENEGEYSER:
		case  UNIT_TYPEID::NEUTRAL_RICHVESPENEGEYSER:case  UNIT_TYPEID::NEUTRAL_PURIFIERVESPENEGEYSER:case UNIT_TYPEID::NEUTRAL_SPACEPLATFORMGEYSER:
			return true;
		}
		return false;
	}

	bool IsWorkerType(sc2::UNIT_TYPEID type)
	{
		switch (type)
		{
		case sc2::UNIT_TYPEID::TERRAN_SCV:
		case sc2::UNIT_TYPEID::TERRAN_MULE:
		case sc2::UNIT_TYPEID::PROTOSS_PROBE:
		case sc2::UNIT_TYPEID::ZERG_DRONE:
		case sc2::UNIT_TYPEID::ZERG_DRONEBURROWED: return true;
		default: return false;
		}
	}

	bool IsCommandStructure(sc2::UNIT_TYPEID type) {
		switch (type) {
		case UNIT_TYPEID::TERRAN_COMMANDCENTER:
		case UNIT_TYPEID::TERRAN_COMMANDCENTERFLYING:
		case UNIT_TYPEID::TERRAN_ORBITALCOMMAND:
		case UNIT_TYPEID::TERRAN_PLANETARYFORTRESS:
		case UNIT_TYPEID::TERRAN_ORBITALCOMMANDFLYING:
		case UNIT_TYPEID::PROTOSS_NEXUS:
		case UNIT_TYPEID::ZERG_HATCHERY:
		case UNIT_TYPEID::ZERG_LAIR:
		case UNIT_TYPEID::ZERG_HIVE: return true;
		default: return false;
		}
	}

	bool isStaticDefense(const sc2::UNIT_TYPEID type) {
		switch (type)
		{
		case sc2::UNIT_TYPEID::ZERG_SPINECRAWLER:
		case sc2::UNIT_TYPEID::ZERG_SPINECRAWLERUPROOTED:
		case sc2::UNIT_TYPEID::PROTOSS_PHOTONCANNON:
		case sc2::UNIT_TYPEID::PROTOSS_SHIELDBATTERY:
		case sc2::UNIT_TYPEID::TERRAN_BUNKER:
		case sc2::UNIT_TYPEID::TERRAN_PLANETARYFORTRESS:
			return true;
		}
		return false;
	}

	bool IsRangedUnit(const sc2::UNIT_TYPEID type)
	{
		switch (type)
		{
		case UNIT_TYPEID::TERRAN_MARINE:
		case UNIT_TYPEID::TERRAN_MARAUDER:
		case UNIT_TYPEID::PROTOSS_ADEPT:
		case UNIT_TYPEID::PROTOSS_STALKER:
		case UNIT_TYPEID::ZERG_ROACH:
			return true;
		}
		return false;
	}

	bool IsBuilding(const sc2::UNIT_TYPEID type)
	{
		if (IsCommandStructure(type)) {
			return true;
		}
		switch (type)
		{
			//Terran
		case sc2::UNIT_TYPEID::TERRAN_ARMORY:
		case sc2::UNIT_TYPEID::TERRAN_BARRACKS:
		case sc2::UNIT_TYPEID::TERRAN_BARRACKSFLYING:
		case sc2::UNIT_TYPEID::TERRAN_BARRACKSREACTOR:
		case sc2::UNIT_TYPEID::TERRAN_BUNKER:
		case sc2::UNIT_TYPEID::TERRAN_BARRACKSTECHLAB:
		case sc2::UNIT_TYPEID::TERRAN_COMMANDCENTER:
		case sc2::UNIT_TYPEID::TERRAN_ENGINEERINGBAY:
		case sc2::UNIT_TYPEID::TERRAN_FACTORY:
		case sc2::UNIT_TYPEID::TERRAN_FACTORYFLYING:
		case sc2::UNIT_TYPEID::TERRAN_FACTORYREACTOR:
		case sc2::UNIT_TYPEID::TERRAN_FACTORYTECHLAB:
		case sc2::UNIT_TYPEID::TERRAN_FUSIONCORE:
		case sc2::UNIT_TYPEID::TERRAN_GHOSTACADEMY:
		case sc2::UNIT_TYPEID::TERRAN_MISSILETURRET:
		case sc2::UNIT_TYPEID::TERRAN_PLANETARYFORTRESS:
		case sc2::UNIT_TYPEID::TERRAN_REFINERY:
		case sc2::UNIT_TYPEID::TERRAN_SENSORTOWER:
		case sc2::UNIT_TYPEID::TERRAN_STARPORT:
		case sc2::UNIT_TYPEID::TERRAN_STARPORTFLYING:
		case sc2::UNIT_TYPEID::TERRAN_STARPORTREACTOR:
		case sc2::UNIT_TYPEID::TERRAN_STARPORTTECHLAB:
		case sc2::UNIT_TYPEID::TERRAN_SUPPLYDEPOT:
		case sc2::UNIT_TYPEID::TERRAN_SUPPLYDEPOTLOWERED:
		case sc2::UNIT_TYPEID::TERRAN_REACTOR:
		case sc2::UNIT_TYPEID::TERRAN_TECHLAB:

			// Zerg
		case sc2::UNIT_TYPEID::ZERG_BANELINGNEST:
		case sc2::UNIT_TYPEID::ZERG_CREEPTUMOR:
		case sc2::UNIT_TYPEID::ZERG_CREEPTUMORBURROWED:
		case sc2::UNIT_TYPEID::ZERG_CREEPTUMORQUEEN:
		case sc2::UNIT_TYPEID::ZERG_EVOLUTIONCHAMBER:
		case sc2::UNIT_TYPEID::ZERG_EXTRACTOR:
		case sc2::UNIT_TYPEID::ZERG_GREATERSPIRE:
		case sc2::UNIT_TYPEID::ZERG_HYDRALISKDEN:
		case sc2::UNIT_TYPEID::ZERG_INFESTATIONPIT:
		case sc2::UNIT_TYPEID::ZERG_LURKERDENMP:
		case sc2::UNIT_TYPEID::ZERG_NYDUSCANAL:
		case sc2::UNIT_TYPEID::ZERG_NYDUSNETWORK:
		case sc2::UNIT_TYPEID::ZERG_SPINECRAWLER:
		case sc2::UNIT_TYPEID::ZERG_SPINECRAWLERUPROOTED:
		case sc2::UNIT_TYPEID::ZERG_SPAWNINGPOOL:
		case sc2::UNIT_TYPEID::ZERG_SPIRE:
		case sc2::UNIT_TYPEID::ZERG_SPORECRAWLER:
		case sc2::UNIT_TYPEID::ZERG_SPORECRAWLERUPROOTED:
		case sc2::UNIT_TYPEID::ZERG_ULTRALISKCAVERN:

			// Protoss
		case sc2::UNIT_TYPEID::PROTOSS_ASSIMILATOR:
		case sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE:
		case sc2::UNIT_TYPEID::PROTOSS_DARKSHRINE:
		case sc2::UNIT_TYPEID::PROTOSS_FLEETBEACON:
		case sc2::UNIT_TYPEID::PROTOSS_FORGE:
		case sc2::UNIT_TYPEID::PROTOSS_PHOTONCANNON:
		case sc2::UNIT_TYPEID::PROTOSS_SHIELDBATTERY:
		case sc2::UNIT_TYPEID::PROTOSS_GATEWAY:
		case sc2::UNIT_TYPEID::PROTOSS_PYLON:
		case sc2::UNIT_TYPEID::PROTOSS_PYLONOVERCHARGED:
		case sc2::UNIT_TYPEID::PROTOSS_ROBOTICSBAY:
		case sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY:
		case sc2::UNIT_TYPEID::PROTOSS_STARGATE:
		case sc2::UNIT_TYPEID::PROTOSS_TEMPLARARCHIVE:
		case sc2::UNIT_TYPEID::PROTOSS_TWILIGHTCOUNCIL:
		case sc2::UNIT_TYPEID::PROTOSS_WARPGATE:
			return true;
		}
		return false;
	}

	bool IsArmyUnitType(const sc2::UNIT_TYPEID type)
	{
		if (IsWorkerType(type)) { return false; }
		if (type == sc2::UNIT_TYPEID::ZERG_OVERLORD) { return false; } //Excluded here the overlord transport etc to count them as army unit
		if (IsBuilding(type)) { return false; }
		if (type == sc2::UNIT_TYPEID::ZERG_EGG) { return false; }
		if (type == sc2::UNIT_TYPEID::ZERG_LARVA) { return false; }
		if (type == sc2::UNIT_TYPEID::PROTOSS_ADEPTPHASESHIFT) { return false; }
		return true;
	}

	bool isChronoed(const sc2::Unit * gw)
	{
		for (auto & buff : gw->buffs) {
			if (buff == sc2::BUFF_ID::TIMEWARPPRODUCTION) {
				return true;
			}
		}
		return false;
	}

	float getRange(const Unit *z, const sc2::UnitTypes & types) {
		auto & arms = types.at(static_cast<uint32_t>(z->unit_type)).weapons;
		if (arms.empty()) {
			return z->radius;
		}
		float attRange = arms.front().range + z->radius;
		if (z->unit_type == UNIT_TYPEID::TERRAN_CYCLONE) {
			attRange *= 2;
		}
		return attRange;
	}

	sc2::Race getRace(sc2::UNIT_TYPEID type) {
		using T = sc2::UNIT_TYPEID;
		switch (type)
		{
		case T::PROTOSS_ADEPT: 
		case T::PROTOSS_ADEPTPHASESHIFT:
		case T::PROTOSS_ARCHON:
		case T::PROTOSS_ASSIMILATOR:
		case T::PROTOSS_CARRIER:
		case T::PROTOSS_COLOSSUS:
		case T::PROTOSS_CYBERNETICSCORE:
		case T::PROTOSS_DARKSHRINE:
		case T::PROTOSS_DARKTEMPLAR:
		case T::PROTOSS_DISRUPTOR:
		case T::PROTOSS_FLEETBEACON:
		case T::PROTOSS_FORGE:
		case T::PROTOSS_GATEWAY:
		case T::PROTOSS_HIGHTEMPLAR:
		case T::PROTOSS_IMMORTAL:
		case T::PROTOSS_INTERCEPTOR:
		case T::PROTOSS_MOTHERSHIP:
		case T::PROTOSS_NEXUS:
		case T::PROTOSS_ORACLE:
		case T::PROTOSS_PHOENIX:
		case T::PROTOSS_PHOTONCANNON:
		case T::PROTOSS_PROBE:
		case T::PROTOSS_PYLON:
		case T::PROTOSS_ROBOTICSBAY:
		case T::PROTOSS_ROBOTICSFACILITY:
		case T::PROTOSS_SENTRY:
		case T::PROTOSS_SHIELDBATTERY:
		case T::PROTOSS_STALKER:
		case T::PROTOSS_STARGATE:
		case T::PROTOSS_TEMPEST:
		case T::PROTOSS_TEMPLARARCHIVE:
		case T::PROTOSS_TWILIGHTCOUNCIL:
		case T::PROTOSS_VOIDRAY:
		case T::PROTOSS_WARPGATE:
		case T::PROTOSS_WARPPRISM:
		case T::PROTOSS_ZEALOT:
			return Race::Protoss;
		case sc2::UNIT_TYPEID::TERRAN_ARMORY:
		case sc2::UNIT_TYPEID::TERRAN_BARRACKS:
		case sc2::UNIT_TYPEID::TERRAN_BARRACKSFLYING:
		case sc2::UNIT_TYPEID::TERRAN_BARRACKSREACTOR:
		case sc2::UNIT_TYPEID::TERRAN_BUNKER:
		case sc2::UNIT_TYPEID::TERRAN_BARRACKSTECHLAB:
		case sc2::UNIT_TYPEID::TERRAN_COMMANDCENTER:
		case sc2::UNIT_TYPEID::TERRAN_ENGINEERINGBAY:
		case sc2::UNIT_TYPEID::TERRAN_FACTORY:
		case sc2::UNIT_TYPEID::TERRAN_FACTORYFLYING:
		case sc2::UNIT_TYPEID::TERRAN_FACTORYREACTOR:
		case sc2::UNIT_TYPEID::TERRAN_FACTORYTECHLAB:
		case sc2::UNIT_TYPEID::TERRAN_FUSIONCORE:
		case sc2::UNIT_TYPEID::TERRAN_GHOSTACADEMY:
		case sc2::UNIT_TYPEID::TERRAN_MISSILETURRET:
		case sc2::UNIT_TYPEID::TERRAN_PLANETARYFORTRESS:
		case sc2::UNIT_TYPEID::TERRAN_REFINERY:
		case sc2::UNIT_TYPEID::TERRAN_SENSORTOWER:
		case sc2::UNIT_TYPEID::TERRAN_STARPORT:
		case sc2::UNIT_TYPEID::TERRAN_STARPORTFLYING:
		case sc2::UNIT_TYPEID::TERRAN_STARPORTREACTOR:
		case sc2::UNIT_TYPEID::TERRAN_STARPORTTECHLAB:
		case sc2::UNIT_TYPEID::TERRAN_SUPPLYDEPOT:
		case sc2::UNIT_TYPEID::TERRAN_SUPPLYDEPOTLOWERED:
		case sc2::UNIT_TYPEID::TERRAN_REACTOR:
		case sc2::UNIT_TYPEID::TERRAN_TECHLAB:
		case T::TERRAN_SCV:
		case T::TERRAN_BANSHEE:
		case T::TERRAN_BATTLECRUISER:
		case T::TERRAN_CYCLONE:
		case T::TERRAN_GHOST:
		case T::TERRAN_HELLION:
		case T::TERRAN_HELLIONTANK:
		case T::TERRAN_LIBERATOR:
		case T::TERRAN_MARAUDER:
		case T::TERRAN_MARINE:
		case T::TERRAN_MEDIVAC:
		case T::TERRAN_MULE:
		case T::TERRAN_RAVEN:
		case T::TERRAN_REAPER:
		case T::TERRAN_SIEGETANK:
		case T::TERRAN_THOR:
			return Race::Terran;
		default :
			return Race::Zerg;
		}
	}

}